name: example
description: Demonstrates how to use the interactive_tables package.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  interactive_tables:
    path: ../

flutter:
  uses-material-design: true
