name: example
description: Demonstrates how to use the power_table package.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  power_table:
    path: ../

flutter:
  uses-material-design: true
